# Generated by Django 4.2 on 2023-05-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='mail',
            field=models.TextField(null=True, verbose_name='Почта'),
        ),
    ]
