# Generated by Django 4.2 on 2023-05-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clients_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='status',
            field=models.IntegerField(default=1, verbose_name='Статус'),
        ),
    ]
