# Generated by Django 4.2 on 2023-05-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clients_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='polis',
            field=models.IntegerField(null=True, verbose_name='ПОЛИС ОМС'),
        ),
    ]
