# Generated by Django 4.2 on 2023-05-01 21:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_clients_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 5, 1, 21, 48, 23, 645797), verbose_name='Время')),
                ('procedure_name', models.TextField(null=True, verbose_name='Процедура')),
                ('cabinet', models.TextField(null=True, verbose_name='Кабинет')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('is_payed', models.IntegerField(default=0, verbose_name='Оплачено')),
                ('is_cancelled', models.IntegerField(default=0, verbose_name='Отменено')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'records',
            },
        ),
    ]
