# Generated by Django 4.2 on 2023-05-02 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 14, 39, 14, 40301), verbose_name='Время'),
        ),
    ]
