# Generated by Django 4.2 on 2023-05-02 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_records_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 15, 11, 8, 357908), verbose_name='Время'),
        ),
    ]
